// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: unary.proto

package unary

import (
	context "context"
	calculation "github.com/Inspirate789/golang-sandbox/internal/adapters/grpc/api/calculation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UnaryCalculatorClient is the client API for UnaryCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnaryCalculatorClient interface {
	Calculate(ctx context.Context, in *calculation.Calculation, opts ...grpc.CallOption) (*calculation.Calculation, error)
}

type unaryCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewUnaryCalculatorClient(cc grpc.ClientConnInterface) UnaryCalculatorClient {
	return &unaryCalculatorClient{cc}
}

func (c *unaryCalculatorClient) Calculate(ctx context.Context, in *calculation.Calculation, opts ...grpc.CallOption) (*calculation.Calculation, error) {
	out := new(calculation.Calculation)
	err := c.cc.Invoke(ctx, "/calculation.UnaryCalculator/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryCalculatorServer is the server API for UnaryCalculator service.
// All implementations must embed UnimplementedUnaryCalculatorServer
// for forward compatibility
type UnaryCalculatorServer interface {
	Calculate(context.Context, *calculation.Calculation) (*calculation.Calculation, error)
	mustEmbedUnimplementedUnaryCalculatorServer()
}

// UnimplementedUnaryCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedUnaryCalculatorServer struct {
}

func (UnimplementedUnaryCalculatorServer) Calculate(context.Context, *calculation.Calculation) (*calculation.Calculation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedUnaryCalculatorServer) mustEmbedUnimplementedUnaryCalculatorServer() {}

// UnsafeUnaryCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnaryCalculatorServer will
// result in compilation errors.
type UnsafeUnaryCalculatorServer interface {
	mustEmbedUnimplementedUnaryCalculatorServer()
}

func RegisterUnaryCalculatorServer(s grpc.ServiceRegistrar, srv UnaryCalculatorServer) {
	s.RegisterService(&UnaryCalculator_ServiceDesc, srv)
}

func _UnaryCalculator_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(calculation.Calculation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryCalculatorServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculation.UnaryCalculator/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryCalculatorServer).Calculate(ctx, req.(*calculation.Calculation))
	}
	return interceptor(ctx, in, info, handler)
}

// UnaryCalculator_ServiceDesc is the grpc.ServiceDesc for UnaryCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnaryCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculation.UnaryCalculator",
	HandlerType: (*UnaryCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _UnaryCalculator_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unary.proto",
}
