apiVersion: v1
kind: Service
metadata:
    labels:
        app: websocket
    name: websocket
spec:
    type: NodePort
    ports:
        -   name: tcp
            port: 30081
            targetPort: 30081
            nodePort: 30081
    selector:
        app: websocket